//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZK.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string LatAndLong { get; set; }
        public string Address { get; set; }
        public int IsDel { get; set; }
        public System.Guid InputUser { get; set; }
        public System.DateTime InsertTime { get; set; }
    }
}
