//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZK.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public System.Guid Id { get; set; }
        public string ScriptName { get; set; }
        public System.Guid MobileType { get; set; }
        public string DPI { get; set; }
        public string ScriptPath { get; set; }
        public string APPName { get; set; }
        public string ScriptContent { get; set; }
        public int IsDel { get; set; }
        public System.Guid InputUser { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
