//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZK.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdmin
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string IdCard { get; set; }
        public string Department { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Mail { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public int State { get; set; }
        public string RoleId { get; set; }
        public Nullable<System.Guid> InputUser { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
