//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZK.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WZKEntities : DbContext
    {
        public WZKEntities()
            : base("name=WZKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppAuthorize> AppAuthorize { get; set; }
        public virtual DbSet<AutoReply> AutoReply { get; set; }
        public virtual DbSet<AutoReplyTemplate> AutoReplyTemplate { get; set; }
        public virtual DbSet<IDCS> IDCS { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<MenuButton> MenuButton { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Mobile> Mobile { get; set; }
        public virtual DbSet<MobileTypes> MobileTypes { get; set; }
        public virtual DbSet<MomentsTemplate> MomentsTemplate { get; set; }
        public virtual DbSet<OperateLog> OperateLog { get; set; }
        public virtual DbSet<PictureAnalysis> PictureAnalysis { get; set; }
        public virtual DbSet<RealtimeControl> RealtimeControl { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Script> Script { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskDetail> TaskDetail { get; set; }
        public virtual DbSet<UserAdmin> UserAdmin { get; set; }
    }
}
